# Generated by Django 2.2 on 2019-12-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191204_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.College'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('course', 'section_code')},
        ),
    ]
